// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrwwdypnioppjydwbgvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yd3dkeXBuaW9wcGp5ZHdiZ3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODIwNjMsImV4cCI6MjA3NDU1ODA2M30.zg7gbKYaWDriVazyP69eoeZOh8uiUfHzL7ntkzV05Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});